import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One sidebar per top-level section. Each doc page picks its sidebar via the
// route it lives under, so the navbar links land on a focused tree.
const sidebars: SidebarsConfig = {
  guideSidebar: [{type: 'autogenerated', dirName: 'guide'}],
  specSidebar: [{type: 'autogenerated', dirName: 'spec'}],
  stdlibSidebar: [{type: 'autogenerated', dirName: 'stdlib'}],
  cliSidebar: [{type: 'autogenerated', dirName: 'cli'}],
  sdkSidebar: [{type: 'autogenerated', dirName: 'sdk'}],
};

export default sidebars;
